#! /bin/sh
PETALS_BIN=/opt/petalsesb/bin

case "$1" in
start)
echo "Starting Petals from $PETALS_BIN"
sudo -u petals nohup $PETALS_BIN/petals-esb.sh &
petals_pid=`echo \`ps aux | grep petals-esb[.sh]\` | gawk '{print $2}'`
if [ $petals_pid != null ] ; then
echo '         _____     _        _        _____ _             _           _ '
echo '        |  __ \   | |      | |      / ____| |           | |         | |'
echo '        | |__) |__| |_ __ _| |___  | (___ | |_ __ _ _ __| |_ ___  __| |'
echo '        |  ___/ _ \ __/ _  | / __|  \___ \| __/ _  |  __| __/ _ \/ _  |'
echo '        | |  |  __/ || (_| | \__ \  ____) | || (_| | |  | ||  __/ (_| |'
echo '        |_|   \___|\__\__ _|_|___/ |_____/ \__\__ _|_|   \__\___|\__ _|'
echo '                                                                       '
fi
;;
restart)
$0 stop
$0 start
;;
stop)
echo "Stopping Petals from $PETALS_BIN"
petals_pid=`echo \`ps aux | grep petals-esb[.sh]\` | gawk '{print $2}'`
wait $petals_pid
sudo -u petals $PETALS_BIN/petals-esb.sh stop
echo '       _____     _        _        _____ _                             _ '
echo '      |  __ \   | |      | |      / ____| |                           | |'
echo '      | |__) |__| |_ __ _| |___  | (___ | |_ ___  _ __  _ __   ___  __| |'
echo '      |  ___/ _ \ __/ _  | / __|  \___ \| __/ _ \|  _ \|  _ \ / _ \/ _  |'
echo '      | |  |  __/ || (_| | \__ \  ____) | || (_) | |_) | |_) |  __/ (_| |'
echo '      |_|   \___|\__\__ _|_|___/ |_____/ \__\___/|  __/|  __/ \___|\__ _|'
echo '                                                 | |   | |               '
echo '                                                 |_|   |_|               '
echo '                                                                         '    
;;
*)
echo $"usage: $0 {start|stop|restart}"
exit 3
;;
esac
:
